import { Aleo, Montserrat } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/admin/Sidebar";
import { AppProvider } from "@/utils/AppContext";
import Header from "@/components/admin/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const aleo = Aleo({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const montserrat = Montserrat({
  subsets: ["latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <AppProvider>
          <div className="flex h-screen overflow-hidden">
            <Sidebar />
            <div className="relative flex flex-1 flex-col overflow-y-auto overflow">
              <Header />
              <div className="">{children}</div>
            </div>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
